require("kobuvim")

require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.autopairs")
require("user.lsp")
require("user.treesitter")
require("user.comment")
require("user.alpha")
require("user.nvimtree")
require("user.bufferline")
require("user.colorizer")
require("user.lualine")
require("user.telescope")
require("user.null-ls")
require("user.gitsigns")
require("user.indent-line")
require("user.todo-comments")

require("user.hot-keys")
